[package]
name = "signal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "main"
path = "src/main.rs" 

[[bin]]
name = "dialog"
path = "src/dialog.rs"

[dependencies]
gtk = "0.17.1"
