[package]
name = "control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "slider"
path = "src/slider.rs"

[dependencies]
chrono = "0.4.26"
gtk = "0.17.1"
