[package]
name = "make_simple_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "image"
path = "src/image.rs"

[[bin]]
name = "image_cmd"
path = "src/image_cmd.rs"

[dependencies]
gtk = "0.17.1"
